[package]
name = "argparse"
version = "0.1.1"
edition = "2021"
authors = ["NewDawn0 (Tom)"]
license = "MIT"
keywords = ["parsing", "argument parsing", "cli parser", "cli argument parser", "parser"]
categories = ["command-line-utilities"]

[dependencies]
